#!/usr/bin/env php
<?php
session_start();

//Import CLI class into the global namespace
use LaswitchTech\coreDB\CLI;

// Define Root Path
define('ROOT_PATH',__DIR__);

//Load Composer's autoloader
require 'vendor/autoload.php';

// Interpret Standard Input
if(defined('STDIN') && !empty($argv)){

  // Start Command
  new CLI($argv);
}
