name: Pre-Release

on:
  push:
    branches: [ pre-release ]

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2
    - uses: ncipollo/release-action@v1
      with:
        name: "22.04-dev.114"
        tag: "pre-release"
        bodyFile: "LATEST.md"
        token: ${{ secrets.GITHUB_TOKEN }}
        prerelease: true