name: Dev

on:
  push:
    branches: [ dev ]

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2
    - uses: ncipollo/release-action@v1
      with:
        name: "22.04-dev.103"
        tag: "dev"
        bodyFile: "LATEST.md"
        token: ${{ secrets.GITHUB_TOKEN }}
        draft: true